baseURL = "https://littleyellow.github.io/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "Dev Notes"
theme = "ananke"
hasCJKLanguage = true
enableEmoji = true

[author]
  name = "Developer"

[params]
  description = "記錄開發路上的坑與頓悟"
  github = "https://github.com/LittleYellow"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name   = "文章"
    url    = "posts/"
    weight = 10

  [[menu.main]]
    name   = "關於"
    url    = "about/"
    weight = 20
